---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}

library(showtext)
theme_set(theme_light())

font_add_google("Lato", family = "lato")

#showtext_auto()

gs_first_round_gdp <- read_csv("../data/results_gdp.csv") %>% 
  #just look up until covid pandemic  (as will have distorted things)
  filter(year < 2020)

gs_first_round_gdp

gs_entries_by_country <- read_csv("../data/gs_entries_by_country.csv") %>% 
  # just look up until covid pandemic  (as will have distorted things)
  filter(year < 2020)

gs_entries_by_country %>% 
  filter(year == 2020)

```
## top 20% countries

### upwards and downward trends

```{r}

plot_df <- gs_entries_by_country %>% 
  mutate(top_20_perc = if_else(is.na(top_20_perc), FALSE, top_20_perc)) %>% 
  group_by(year, top_20_perc) %>% 
  summarise(num_first_rd = sum(num_first_rd)) %>% 
  ungroup() %>% 
  
  group_by(year) %>% 
  mutate(perc_first_round = num_first_rd / sum(num_first_rd)) %>% 
  ungroup()
  
p <-  ggplot(plot_df) +
  geom_area(aes(year, perc_first_round, fill = top_20_perc)) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1L),
                       expand = c(0,0)) +
    scale_x_continuous(expand = c(0,0), 
                       breaks=c(1990,1995,2000,2005,2010,2015,2019)) +
    coord_cartesian(clip = 'off') +
  labs(x = NULL, y = NULL) +
  theme(legend.position = "none",
        plot.margin = margin(25,25,25,25)) 

p 
#plotly::ggplotly(p)

ggsave("../images/all_gs.svg", units = "mm", width = 600, height = 325)
  
filter(plot_df, top_20_perc)
```


### How have top 20% countries changed or not?

```{r}

top_twenty_countries <- gs_entries_by_country %>% 
  filter(top_20_perc) %>% 
  count(year, country, wt = num_first_rd) %>% 
  arrange(year, desc(n)) %>% 
  group_by(country) %>% 
  mutate(country_ave_n = mean(n)) %>% 
  ungroup()

country_ave_ns <- top_twenty_countries %>% 
  distinct(country, country_ave_n)
  
# look at how many time the countries appear in the top twenty percent
top_twenty_counts <- top_twenty_countries %>% 
  count(country) %>% 
  left_join(country_ave_ns) %>% 
  arrange(desc(n), desc(country_ave_n)) %>% 
  rename(years_top_20 = n)
  

# for ordering exploratory plot
levels <- top_twenty_counts$country
  
# ggplot(top_twenty_countries) +
#   geom_tile(aes(x = year, 
#                 y = factor(country, levels = rev(levels)),
#                 fill = n),
#             colour = "#F8F7F7") +
#   labs(x= NULL, y = NULL) +
#   
#   coord_equal() +
#   
#   scale_fill_gradient(low = "#D6DCE0", high = "#000DA8", trans = "log") +
#   theme_minimal() +
#   theme(legend.position = "none")


# create a grid to see where countries have moved out of top 20 perc
grid <-  expand_grid(year = unique(top_twenty_countries$year),
                     country = unique(top_twenty_countries$country))
plot_df <- grid %>% 
  left_join(top_twenty_countries)

# deciles by year
bottom_80_countries_by_year <- gs_entries_by_country %>% 
  distinct(year, country, income_decile) %>% 
  filter(income_decile < 9)

check_bottom_80 <- function(year, country){

  selector <- bottom_80_countries_by_year$year == year & 
              bottom_80_countries_by_year$country == country
  
  res <- bottom_80_countries_by_year[selector, ]
  
  if(nrow(res) == 0){
    return(FALSE)
    }
  else {
    return(res[[1,"income_decile"]] < 9)
  }
}

check_bottom_80(1990, "Nigeria")

plot_df_1 <- plot_df %>% 
  mutate(in_bottom_80 = map2_lgl(year, country, ~check_bottom_80(.x,.y)),
         n = if_else(is.na(n) & in_bottom_80,
                     -1, n),
         n = replace_na(n, 0),
         bin_n = cut(n, breaks = c(-Inf, -1e-10,0,1e10, 10, 50, 100, Inf)))  


p <-   ggplot(plot_df_1) +
    geom_tile(aes(x = year, 
                  y = factor(country, levels = rev(levels)),
                  fill = bin_n),
              colour = "#F8F7F7") +
    labs(x= NULL, y = NULL) +
    
    coord_equal() +
    guides(fill = guide_legend(reverse=TRUE)) +
    
    
      # https://gka.github.io/palettes/#/5|s|ffffff,35469d|ffffe0,ff005e,93003a|1|1
  scale_fill_manual(values = c("#E7E4E5", "white", '#cfcde7', '#9f9dce', '#6e70b6', '#35469d')) +
    
    #scale_fill_gradient(low = "#D6DCE0", high = "#000DA8") +
    scale_x_continuous(position = "top") +
    theme_minimal()
  
p
ggsave("../images/image_4.svg")

# a quick test
gs_entries_by_country %>% 
  filter(country == "Israel") %>% 
  distinct(year, income_decile)
```
### downward trend

```{r}

all_gs_entries_by_country <- gs_entries_by_country %>% 
  
  group_by(year, country) %>% 
  mutate(num_first_rd_year = sum(num_first_rd)) %>% 
  ungroup() %>% 
  
  select(-c(tourney_name, num_first_rd)) %>% 
  distinct() %>% 
  
  group_by(year) %>% 
  mutate(perc_first_round = num_first_rd_year / sum(num_first_rd_year)) %>% 
  ungroup()


gs_entries_top_20_perc <- all_gs_entries_by_country %>% 
  filter(top_20_perc)

grid <- expand_grid(year = unique(gs_entries_top_20_perc$year),
                    country = unique(gs_entries_top_20_perc$country))
  
plot_df <- grid %>% 
  left_join(gs_entries_top_20_perc) %>% 
  mutate(perc_first_round = replace_na(perc_first_round, 0)) %>% 
  filter(year <= 2008) %>% 
  mutate(is_usa = country == "United States")
  
change_df <- plot_df %>% 
  filter(year == max(year) | year == min(year)) %>% 
  select(year, country, perc_first_round) %>% 
  
  pivot_wider(names_from = year,
              values_from = perc_first_round,
              values_fill = 0) %>% 
  mutate(change = `2008` - `1990`,
         fall = change < 0,
         change_bin = cut(change, breaks = c(-Inf, -0.1, -0.02, 0.02, 0.1, Inf))) %>% 
  arrange(change)

plot_df_1 <- plot_df %>% 
  left_join(change_df) %>% 
  group_by(country) %>% 
  mutate(ave_num_first_round = mean(num_first_rd_year, na.rm = TRUE)) %>% 
  ungroup() %>% 
  # mutate(country = fct_reorder(country, ave_num_first_round, change,
  #                              .fun = "median"))
  arrange(fall, desc(change)) %>% 
  mutate(country = factor(country, levels = unique(country)),
         )


#visdat::vis_miss(plot_df, warn_large_data = FALSE)

p <- ggplot(plot_df_1) +
  geom_area(aes(year, perc_first_round,
                group = country,
                fill = change_bin),
            colour = "grey80", size = 0.2) +
  #scale_fill_gradient2(low = "#C94A54", mid = "white", high = "#35469D") #+
  # reds from https://gka.github.io/palettes/#/8|s|c94a54,fffff0|ffffe0,ff005e,93003a|1|1
  # blue from https://gka.github.io/palettes/#/8|s|35469d,fffff0|ffffe0,ff005e,93003a|1|1
    scale_fill_manual(values = c("#c94a54", "#efb3aa", "#fffff0", "#aeabcd")) +
  
    scale_y_continuous(labels = scales::percent_format(accuracy = 1L),
                       breaks = c(seq(0,0.8,0.1)),
                       expand = expansion(mult = c(0, .1))) +
  
    scale_x_continuous(expand = c(0,0), 
                       breaks=c(1990,1995,2000,2005,2008)) +
  
    # coord_cartesian(clip = 'off') +
  labs(x = NULL, y = NULL) +
  theme(legend.position = "none",
        plot.margin = margin(25,25,25,25)) 
  #facet_wrap(~is_usa)

p

ggsave("../images/image_5.svg", units = "mm", width = 500, height = 300)

plotly::ggplotly(p)

```

### upward trend

```{r}
plot_df <- grid %>% 
  left_join(gs_entries_top_20_perc) %>% 
  mutate(perc_first_round = replace_na(perc_first_round, 0)) %>% 
  filter(year > 2008)

change_df <- plot_df %>% 
  filter(year == max(year) | year == min(year)) %>% 
  select(year, country, perc_first_round) %>% 
  
  pivot_wider(names_from = year,
              values_from = perc_first_round,
              values_fill = 0) %>% 
  mutate(change = `2019` - `2009`,
         fall = change < 0,
         change_bin = cut(change, breaks = c(-Inf, -0.1, -0.02, 0.02, 0.1, Inf))) %>% 
  arrange(change)

countries_of_int <-  c("United States", "France", "Sweden", "Australia", "Spain")

plot_df_1 <- plot_df %>% 
  left_join(change_df) %>% 
  mutate(country = if_else(country %in% countries_of_int, country, "Other")) %>% 
  group_by(country, year) %>%
  summarise(perc_first_round = sum(perc_first_round)) %>% 
  ungroup()
  
facet_order <- c("United States", "Australia", "Sweden", "France", "Spain", "Other")

# annotation df
annotation_df <- plot_df_1 %>% 
  mutate(label = round(perc_first_round * 100, 1),
         num_appearances = round(perc_first_round * 256)) %>% 
  filter(year == max(plot_df_1$year)|
           year == min(plot_df_1$year))

p <- ggplot(plot_df_1,
            aes(year, perc_first_round)) +
  geom_area(aes(group = country),
            colour = "grey80", size = 0.2) +
  ggrepel::geom_text_repel(data = annotation_df,
                           mapping = aes(label = num_appearances)) +
  
  facet_wrap(~factor(country, levels = facet_order))

p
```




### country affects
```{r}

gs_first_round_gdp %>% 

  count(year, country, iso) %>% 
  group_by(year) %>% 
  mutate(perc_appear = n / sum(n)) %>% 
  
  filter(iso %in% c("USA", "FRA", "ESP")) %>% 
  
  ggplot() +
  geom_line(aes(year, perc_appear, colour = country))
```
```{r}

top_3 <- gs_first_round_gdp %>% 
  count(year, country) %>% 
  arrange(year, desc(n)) %>% 
  group_by(year) %>% 
  mutate(rank = rank(-n)) %>% 
  ungroup() %>% 
  
  filter(rank == 1 | rank == 2 | rank == 3)



```

## Countries outside top twenty percent

```{r}
gs_entries_the_other_80 <- gs_entries_by_country %>% 
  filter(!top_20_perc) %>% 
  count(year, country, wt = num_first_rd)

grid <- expand_grid(country = unique(gs_entries_the_other_80$country),
                    year = unique(gs_entries_the_other_80$year))

plot_df <- grid %>%
  left_join(gs_entries_the_other_80) %>%
  mutate(n = replace_na(n, 0))

p <- ggplot(plot_df,
       aes(year, n, group = country)) +
  geom_line()

p
plotly::ggplotly(p)

p <- ggplot(plot_df,
       aes(year, n, fill = country)) +
  geom_area()

p
plotly::ggplotly(p)

```

```{r}
gs_entries_by_country %>% 
  filter(str_detect(str_to_lower(country), "cz"))

```

```{r}
countries_of_int <- c("Russia", "Argentina", "Czechia")

plot_df %>% 
  
  mutate(colour = if_else(country %in% countries_of_int,
                          country, "other")) %>% 
  
  filter(!(country == "Czechia" & year >= 2017)) %>% 
  
  ggplot(aes(year, n, 
             colour = colour, 
             group = country)) +
    geom_step() +
  
    scale_colour_manual(values = c("#A7BCD6", "#35469D", "grey95", "#C94A54")) +
    theme()
```

## Bottom 50 percent
```{r}
bottom_50_perc <- gs_entries_by_country %>% 
  filter(income_decile <= 5)

# num countries with first round appearances 
bottom_50_perc %>% 
  distinct(year, country) %>% 
  count(year) %>% 
  ggplot() +
    geom_col(aes(year, n))

# countries from bottom 50 percent with most appearances in first round 1990 - 2019
top_n <- 5

top_n_countries <- bottom_50_perc %>% 
  count(country) %>% 
  slice_max(order_by = n, n = top_n) %>% 
  .$country

bottom_50_perc %>% 
  distinct(year,country) %>% 
  filter(year == max(year)) %>% 
  .$country

plot_df <- bottom_50_perc %>% 
  count(year, country) %>% 
  mutate(country = if_else(country %in% top_n_countries,
                           country,
                           "Other")) %>% 
  group_by(year, country) %>% 
  summarise(n = sum(n))

ggplot(plot_df) +
  geom_col(aes(year, n, fill = country))
```

```{r}
bottom_50_perc_country_counts <- bottom_50_perc %>% 
  count(year, country, wt = num_first_rd) %>% 
  group_by(country) %>% 
  mutate(country_ave_n = mean(n, na.rm = TRUE)) %>% 
  ungroup()


# look at how many times the countries appear in the bottom fifty percent
bottom_50_summary <- bottom_50_perc_country_counts %>% 
  count(country) %>% 
  rename(total_n = n) %>% 
  left_join(distinct(
              bottom_50_perc_country_counts,
              country,
              country_ave_n
              )) %>% 
  arrange(desc(total_n), desc(country_ave_n))

# bottom_50_perc_country_counts <- bottom_50_perc_country_counts %>% 
#   left_join(bottom_50_summary)
  
# create a grid to see where countries have moved out of bottom 50 perc
grid <-  expand_grid(year = unique(bottom_50_perc_country_counts$year),
                     country = unique(bottom_50_perc_country_counts$country))
plot_df <- grid %>% 
  left_join(bottom_50_perc_country_counts)

# deciles by year
top_50_countries_by_year <- gs_entries_by_country %>% 
  distinct(year, country, income_decile) %>% 
  filter(income_decile > 5)

check_top_50 <- function(year, country){

  selector <- top_50_countries_by_year$year == year & 
              top_50_countries_by_year$country == country
  
  res <- top_50_countries_by_year[selector, ]
  
  if(nrow(res) == 0){
    return(FALSE)
    }
  else {
    return(res[[1,"income_decile"]] > 5)
  }
}

check_top_50(1991, "United States")

plot_df_1 <- plot_df %>% 
  mutate(in_top_50 = map2_lgl(year, country, ~check_top_50(.x,.y)),
         n = if_else(is.na(n) & in_top_50,
                     -1, n),
         n = replace_na(n, 0),
         bin_n = cut(n, breaks = c(-Inf, -1e-10,0,1e10, 5, 10, 20, Inf)))


# for ordering exploratory plot
levels <- rev(bottom_50_summary$country)

ggplot(plot_df_1) +
  geom_tile(aes(x = year, 
                y = factor(country, levels = levels),
                fill = bin_n),
            colour = "#E7E4E5") +
  labs(x= NULL, y = NULL) +
  
  coord_equal() +
  
  # https://gka.github.io/palettes/#/5|s|ffffff,35469d|ffffe0,ff005e,93003a|1|1
  scale_fill_manual(values = c("#E7E4E5", "white", '#cfcde7', '#9f9dce', '#6e70b6', '#35469d')) +
  
  #scale_fill_gradient(low = "#D6DCE0", high = "#000DA8") +
  theme_minimal() +
  theme()

ggsave("test_out.svg")
```

